### ISSUE TITLE
Broken because "willie" has changed to "sopel"

### ISSUE THREAD

**Issue by jacnoc** [gehsekky/sopel-quote#3]
> Error loading quote: No module named 'willie' (../../.sopel/modules/willie-quote/quote.py:23)

Willie (http://github.com/embolalia/willie) has changed to Sopel (http://github.com/embolalia/sopel)

**Comment by gehsekky** [comment]
i've been slacking on updating this for the sopel change, but i'll update it within the next few days.

**Comment by gehsekky** [comment]
just updated it to work with sopel. closing ticket. let me know if you have any other issues!
